### ISSUE TITLE
Datapoints for the room in which the timer was started

### ISSUE THREAD

**Issue by macstone23** [MiRo1310/ioBroker.alexa-timer-vis#1]
Great adapter! A small feature request: It would be great to also have datapoints for the room in which a timer has been started. Could you add that? Thanks! :-)

**Comment by MiRo1310** [comment]
I have just uploaded a new Version, please try.

**Comment by macstone23** [comment]
Great, thanks a lot. I'll test during the weekend.

**Comment by MiRo1310** [comment]
@macstone23 
Does it work, as you wanted ?

**Comment by macstone23** [comment]
> @macstone23 Does it work, as you wanted ?

Works perfectly, thanks a lot! :-)
