### ISSUE TITLE
alive state geht nicht auf true

### ISSUE THREAD

**Issue by maxxe88** [MiRo1310/ioBroker.alexa-timer-vis#102]
Hallo,

wenn ein Timer gestellt wird, wechselt der alive state nicht auf true. Gibt es da abhilfe?
![grafik](https://github.com/MiRo1310/ioBroker.alexa-timer-vis/assets/37014501/9b8b1598-d158-4e2c-bfa3-aaadb63800e8)

Grüße

**Comment by MiRo1310** [comment]
Werde ich mir anschauen.

**Comment by MiRo1310** [comment]
Also ich habe mir das gerade mal angeschaut, aber hier läuft das ganz normal, wäre wir auch aufgefallen, da ich darüber in meiner vis die Anzeige der Timer einblende. Bist du auf der aktuellsten Version? Evtl. einmal deinstallieren und neu installieren. Dein System ist aktuell? Kam der Fehler erst nach einem update?

**Comment by maxxe88** [comment]
Guten Morgen, vielen dank das du danach geschaut hast, Ich habe das System komplett neu aufgesetzt. Ohne Backup oder sonstiges. Es läuft auf einem Proxmox Container. Jetzt als ich nach geschaut habe läuft es auch. Ich hab nichts verändert. 

Aber wenn ich dich jetzt schon an der Strippe habe. Ist es möglich, wieder "00" anzuzeigen? Ich sende die Werte an eine Wled Matrix und wenn da der Timer unter einer Minute ist steht immer nur noch ":23" da anstatt wie früher "00:23". Eventuell ist es auch nur eine Einstellungssache.

Danke

**Comment by MiRo1310** [comment]
Schaue ich mal nach

**Comment by MiRo1310** [comment]
Um welchen Datenpunkt geht es denn eigentlich? Um hour minute und second?

**Comment by maxxe88** [comment]
In meinem um minute. Der Datenpunkt ist ja einfach leer wenn keine Minute mehr vorhanden ist. In der Version davor standt dann glaube ich 00 drin.

**Comment by nobby110** [comment]
Leider funktioniert es bei mir auch nicht mehr. Habe den Adapter schon de- und wieder installiert. Der "Fehler" deckt sich mit dem von maxxe88.

**Comment by MiRo1310** [comment]
Das ist sehr komisch. Das System ist aktuell? Test der Fehler nach einem Update auf ? Sind Fehler im log ?

**Comment by nobby110** [comment]
Das Log nach dem Neustart des Adapters:
![Alexa_Timer1](https://github.com/MiRo1310/ioBroker.alexa-timer-vis/assets/24960413/3ffe3e5b-9cb1-4a79-8e96-4d0982c2da24)

Das System ist aktuell.

![image](https://github.com/MiRo1310/ioBroker.alexa-timer-vis/assets/24960413/bad2ea95-e9a0-4a83-97f1-6aae942f04b1)

**Comment by MiRo1310** [comment]
Und auch beim setzen eines Timers kommt kein Fehler im Log? Und der Datenpunkt wird nicht gesetzt?
Was ist mit dem Sytem? Welche Node.js Version? Usw.?

**Comment by nobby110** [comment]
Beim setzen eines Timers passiert gar nichts im Log. Ich habe die Instanz auf "Debug" gestellt.
nodejs v18.17.1
npm 10.7.0

Debian GNU/Linux 11 (bullseye) x86_64
Kernel: 5.10.0-27-amd64

**Comment by maxxe88** [comment]
Liegt es eventuell an diesen Einstellungen?
![grafik](https://github.com/MiRo1310/ioBroker.alexa-timer-vis/assets/37014501/be31055c-7a4f-4d68-9da5-1891e8a8ecf4)

Müsste alles aktuell sein.
![grafik](https://github.com/MiRo1310/ioBroker.alexa-timer-vis/assets/37014501/78841972-efe4-456d-9e34-949a789247b0)

Hab eben nochn Timer gestartet. Der wird nicht erkannt. Summary bleibt leer und wird nicht aktualisiert.
![grafik](https://github.com/MiRo1310/ioBroker.alexa-timer-vis/assets/37014501/4816da54-a92d-4b0d-b34b-53b77857f673)

edit: Es ist wie verhext, jetzt geht es wieder.

**Comment by MiRo1310** [comment]
Es kann sein das der Timer nicht erkannt wird wenn der Alexa 2.0 Adapter keine Aktualisierung sendet. 

Was heißt jetzt geht es wieder? Das der Datenpunkt auf true geht ? Oder das ein Timer erstellt wird

**Comment by maxxe88** [comment]
Beides. Der summary wird aktualisiert und ein Timer wird gestellt.

Ich habe es jetzt mal getestet. Es liegt definitiv an diesem Punkt. Sobald er angehakt ist geht es.
![grafik](https://github.com/MiRo1310/ioBroker.alexa-timer-vis/assets/37014501/49b89d8f-c673-4830-953d-0ca9de20ab0c)

**Comment by MiRo1310** [comment]
Ja genau der muss gesetzt sein. Das wurde beim Update aber auch angezeigt das es ein Breaking change ist. 
Also vom Alexa 2 Adapter

**Comment by maxxe88** [comment]
Oh mist, dann muss ich das damals überlesen haben. Ich hab mein System komplett neu aufgesetzt und standardmäßig ist der ja deaktiviert. Vielen dank für deinen Support. Wenn jetzt das mit den Minuten noch klappen würde wäre ich super glücklich :)

**Comment by MiRo1310** [comment]
Ja da werde ich mich drum kümmern. Wahrscheinlich wird es möglich sein das man dann in den Settings wählen kann was dort stehen soll wenn der Wert 0 ist.

**Comment by nobby110** [comment]
> Ja genau der muss gesetzt sein. Das wurde beim Update aber auch angezeigt das es ein Breaking change ist. Also vom Alexa 2 Adapter

Upps. Habe ich wohl auch überlesen. Vielleicht könntest Du Deine Doku für "Überleser" ergänzen. Vielen Dank für Deinen schnellen Support. Im Log erscheinen jetzt wieder Meldungen. ;) Ich teste es später ....


NACHTRAG: Funktioniert wieder

**Comment by maxxe88** [comment]
> Ja da werde ich mich drum kümmern. Wahrscheinlich wird es möglich sein das man dann in den Settings wählen kann was dort stehen soll wenn der Wert 0 ist.

Vielen lieben dank
