### ISSUE TITLE
Timeränderung (Dauer) wird ein 2. Timer angelegt

### ISSUE THREAD

**Issue by djmarc75** [MiRo1310/ioBroker.alexa-timer-vis#11]
Hi,
toller Adapter aber wenn ich einen laufenden Timer ändere (in meinem Fall: Alexa, verlängere Timer um 2 Minuten) wird ein zusätzlicher Timer (in meinem Fall mit 2 Minuten) angelegt. 
Das kann man sicher beheben.
Grüße

**Comment by MiRo1310** [comment]
@djmarc75 
oh das geht leider noch nicht, ich war da etwas zu voreilig

**Comment by MiRo1310** [comment]
@djmarc75 Im Moment darf nur ein Timer gestellt sein, ich arbeite daran das mal auch aus mehreren auswählen kann.
Ich würde dich bitten das so aber erstmal zu testen.

**Comment by djmarc75** [comment]
Die Funktionen "Timer verlängern/verkürzen" funktionieren sehr gut.
Allerdings fehlt beim "verlängern" die passende Logausgabe. Beim Verkürzen passt es.
`<html><body>


alexa-timer-vis.0 | 2022-07-02 12:04:20.139 | info | Voice input: verkürze timer um zwei minuten
-- | -- | -- | --
alexa-timer-vis.0 | 2022-07-02 12:04:20.138 | info | Timer soll hinzugefügt werden!
alexa-timer-vis.0 | 2022-07-02 12:04:20.138 | info | Kommando gefunden um Timer zu steuern!
alexa-timer-vis.0 | 2022-07-02 12:04:05.006 | info | Kommando gefunden um Timer zu steuern!
alexa-timer-vis.0 | 2022-07-02 12:03:42.941 | info | Voice input: stelle timer auf zwanzig minuten
alexa-timer-vis.0 | 2022-07-02 12:03:42.940 | info | Timer soll hinzugefügt werden!
alexa-timer-vis.0 | 2022-07-02 12:03:42.940 | info | Kommando gefunden um Timer zu steuern!


</body>
</html>`

Zeile 4 war der Befehl "verlängere Timer um 2 Minuten" und Zeile 3 "verkürze Timer um2 Minuten". Zeile 2 müsste die Ausgabe dementsprechend dann "Timer soll verkürzt werden" (oder ähnlich) sein.

**Comment by MiRo1310** [comment]
@djmarc75 

Verkürzen kann der Code noch nicht, ich habe aber die Ausgabe schon eimal hinzu gefügt.
An dem anderen bin ich noch dran.
