### ISSUE TITLE
"createDevice" abgekündigt in js-controller 7

### ISSUE THREAD

**Issue by Siggi0904** [MiRo1310/ioBroker.alexa-timer-vis#117]
Hallo,

mit der aktuelles js-controller version 6 kommt folgender Hinweis beim neu Anlegen eines Timers.

`2024-08-18 11:08:17.618 - info: alexa-timer-vis.0 (697060) Method "createDevice" is deprecated and will be removed in js-controller 7, use "extendObject/setObjectNotExists" instead`

Bitte die Funktion umstellen.

**Comment by MiRo1310** [comment]
Top. Danke für den Hinweis

**Comment by Siggi0904** [comment]
Die Meldung Method `createDevice" is deprecated and will be removed in js-controller 7, use "extendObject/setObjectNotExists` instead kommt mit der neuen Version 1.0.0 leider immer noch.

Ich habe heute die Stable erhalten.

**Comment by MiRo1310** [comment]
Das ist da auch noch nicht drin.

**Comment by Siggi0904** [comment]
okay, hab es in den Release Notes gesehen.
Sorry.

**Comment by MiRo1310** [comment]
Kein Problem. Hast du das andere schon ausprobiert? Dazu musst du natürlich über den anderen link installieren.

**Comment by Siggi0904** [comment]
Nein, hatte ich nicht. Das möchte ich aus der Ferne nicht machen.
Da warte ich auf die Stable.

Was bedeutet eigentlich die folgende Einstellung, bzw. was trage ich da ein?
![grafik](https://github.com/user-attachments/assets/1df3541d-be5f-43ca-98d8-e5fa3266ec62)
