### ISSUE TITLE
Feature Request: Name des Timers aus entsprechender Alexa lesen

### ISSUE THREAD

**Issue by Siggi0904** [MiRo1310/ioBroker.alexa-timer-vis#118]
Bitte den Namen des Timers aus dem Datenpunkt `alexa2.0.Echo-Devices.G0xxxxxx.Timer.activeTimerList` lesen.

Dieser ist zuverlässiger als aus dem Datenpunkt `alexa2.0.History.summary` zu extrahieren.

Danke.

**Comment by MiRo1310** [comment]
Das Problem ist heraus zu finden welcher Timer genau in der Liste gemeint ist. Bei nur einem Timer kein Problem. Ich schaue mal ob ich was raus finden kann. Vielleicht hast du ja noch eine Idee.

**Comment by Siggi0904** [comment]
Naja, wenn du nur die json aus dem o.g. Zeitpunkt liest, ist doch alles dabei.
Zeit, Name und welche Alexa ist ja alles dann lesbar.

**Comment by MiRo1310** [comment]
Das ist aber ein Array. Wenn du zwei Timer hast müsste ich erst die trigger time berechnen um zu schauen welches das genau ist. Oder bekommt man irgendwo die id des Timers ?

**Comment by Siggi0904** [comment]
hm, vielleicht `alexa2.0.Echo-Devices.G0922M0xxxxxxxx0ARC.Timer.nextTimerId` ?
und `alexa2.0.History.name` sagt dir welche Alexa es ist.

Nur so Ideen.

**Comment by MiRo1310** [comment]
Next Timer sagt welcher als nächstes getriggert werden soll. Das ist aber nicht der Timer unbedingt der als nächstes ab läuft. Ich überlege mir was.

**Comment by MiRo1310** [comment]
Ich habe zum Beispiel auch das Problem das wenn ich in der Küche einen Timer stelle , komischerweise der Timer auf ganz anderen Geräten ausgeführt wird.

**Comment by MiRo1310** [comment]
Das ganze dauert noch ein wenig, ich baue gerade den ganzen Adapter um auf Typescript

**Comment by Siggi0904** [comment]
Kein Thema, was lange währt, wird gut. :-)

**Comment by MiRo1310** [comment]
So ich habe den ersten Test bei mir durch und könnte so funktionieren, wenn du magst bitte über die Katze mit diesem Link testen https://github.com/MiRo1310/ioBroker.alexa-timer-vis/tree/FIX--%23118-Get-Name. Bitte kurzes Feedback
