### ISSUE TITLE
Formatierung von hour, minute und second bei 0 Werten

### ISSUE THREAD

**Issue by BernhardLinz** [MiRo1310/ioBroker.alexa-timer-vis#13]
Ich nutze für die VIS-Anzeige die Einzelwerte der jeweiligen Timer.
Nun ist es so das bei abgelaufenden Timern manchmal, beim timer2 eigentlich immer ein "0" statt "00" genommen wird:
![image](https://user-images.githubusercontent.com/31903932/169968053-39363ccd-4f08-4372-9e3a-c2f1efcf476f.png)
![image](https://user-images.githubusercontent.com/31903932/169968170-066f6147-5c95-466c-880f-526114fe1ae1.png)

könntest du da mal kontrollieren.
Stört zwar nur den inneren Monk, ich wollte deswegen aber auch nicht extra noch mal ein Skript laufen lassen

**Comment by BernhardLinz** [comment]
Nachtrag:
wie man im Screenshot sieht ist auch der String bei timer2 anders als bei den anderen Timern.
Eigentlich bräuchte ich genau den String, nur ohne das Std dahinter.
Eventuell wäre ja eine Möglichkeit in den Optionen des Adapters den String zu konfigurieren

- führende 0 ja oder nein
- Auswahl des Trennzeichens, z.B. ":" oder " : ", also nicht nur ein Zeichen sondern auch Zeichenkette möglich
- Präfix und Suffix
Dann könnte jeder den Wunschstring bauen den er braucht

**Comment by MiRo1310** [comment]
Hi 
Ja das werde ich mir anschauen.

**Comment by MiRo1310** [comment]
@BernhardLinz 
Eigentlich kann das nicht sein. Denn alles läuft in einer Schleife ab. 

Lösch doch mal Timer2 und starte den Adapter neu.

**Comment by BernhardLinz** [comment]
Dann erstellt er die Datenpunkte brav neu - mit 0 statt 00
Version ist v0.1.13, noch mal extra geprüft

**Comment by BernhardLinz** [comment]
Nachtrag: Die anderen Timer erstellt er auch mit 0 statt 00 neu

**Comment by MiRo1310** [comment]
@BernhardLinz 
Sollte jetzt weg sein

**Comment by BernhardLinz** [comment]
Ich sehe keine neue Version, die bestehende nochmal drüber bügeln?

**Comment by MiRo1310** [comment]
@BernhardLinz 
Da ist auch keine neue Version, du musst einmal über die Katze installieren. Und vorher die Ordner im Adapter löschen.

**Comment by BernhardLinz** [comment]
Ordner im iobroker-Ordner löschen oder meinst du die Datenpunkte unter Objekte?

**Comment by MiRo1310** [comment]
@BernhardLinz 
Ja genau

**Comment by BernhardLinz** [comment]
Bei 2 verschiedenen Vorschlägen ist "Ja genau" nicht zielführend ...

**Comment by MiRo1310** [comment]
@BernhardLinz 
Das ist wenn ich das zwischendurch kommentiere. 🤣
Unter Objekte die Timer löschen, damit diese neu erstellt werden müssen.

**Comment by BernhardLinz** [comment]
Also timer2 bis timer4 hat er korrekt mit "00" neu erstellt, bei timer1 ist es immer noch "0"
![image](https://user-images.githubusercontent.com/31903932/171376013-a1f2ae39-ebf3-4e52-9c11-4f28867b5626.png)

**Comment by MiRo1310** [comment]
@BernhardLinz 
Okay 
Aber sobald der erste Timer aufgerufen wird passt alles? 

Das andere ändere ich noch 


Habe den Fehler schon gefunden. Das ist aber nur ein Problem beim ersten erstellen. Danach müsste alles passen.

**Comment by BernhardLinz** [comment]
Jepp, danach passt es
