### ISSUE TITLE
Second Timer Reset deletes also the first Timer

### ISSUE THREAD

**Issue by Heinz2100** [MiRo1310/ioBroker.alexa-timer-vis#132]
I use Version 2.0.2

If I set two timers on Alexa and then delete the second one by resetting the adapter, the first timer is also deleted at the same time.
But this only happens with the second timer. For example, if I reset the fourth timer, then only the fourth one is actually deleted.

**Comment by MiRo1310** [comment]
Du meinst beim drücken des Buttons wird der erste Timer mit gelöscht? Du schreibst resetting des adapters. Deswegen frage ich mal nach

**Comment by Heinz2100** [comment]
Falsch ausgedrückt: Wenn ich bei timer2 den Datenpunkt auf "Reset" auf "true" setze, dann wird im Adapter auch der timer1 gelöscht. Auf Alexa läuft der Timer aber weiter

**Comment by MiRo1310** [comment]
Okay dann weiß ich Bescheid

**Comment by Heinz2100** [comment]
Danke für die schnelle Bearbeitung. Ich habe jetzt alles ausprobiert und es bleibt folgender Fehler: Wenn man einen Timer gleich benennt wie er schon vorher einmal hieß (z.B. Timer1 = Tee-Timer), dann funktioniert der Reset=True nicht.

Alexa antwortet dann: "Du hast bereits einen Timer mit dem Namen Tee-Timer gestellt" und der Timer läuft ganz normal weiter
Im Adapter wird der Timer aber gelöscht

**Comment by MiRo1310** [comment]
Schaue ich mir noch mal an

**Comment by MiRo1310** [comment]
Ich versuche das gerade nach zu stellen, aber ich kann bei mir gar keine 2 gleich genannten Timer erstellen. Vielleicht kannst du mir da noch mal weiter helfen

**Comment by Heinz2100** [comment]
Stell mal einen Timer zum Beispiel mit dem Namen Tee-Timer. Dann Reset mit Datenpunkt.
Danach stell noch einmal einen Tee-Timer. Wenn du den dann mit dem Datenpunkt Reset löschen willst, dann sagt Alexa, dass bereits ein Timer mit dem Namen Tee-Timer gestellt ist statt ihr zu löschen. Im Adapter ist der Timer dann gelöscht, aber auf Alexa läuft er weiter.

**Comment by Heinz2100** [comment]
Ich denke du greifst beim Erstellen der Timer im Adapter nur auf den Namen zurück, oder? Vielleicht müsstest du auch noch den Erstellzeitpunkt mit übergeben, damit es ein eindeutiger Schlüssel wird.

**Comment by MiRo1310** [comment]
Ah okay. Werde ich noch mal probieren

**Comment by MiRo1310** [comment]
Wenn die Tests gleich durch gelaufen sind werde ich das in den main mergen, dann bitte noch einmal testen
