### ISSUE TITLE
Timer Names are not correct

### ISSUE THREAD

**Issue by Heinz2100** [MiRo1310/ioBroker.alexa-timer-vis#133]
I use Version 2.0.2

For me, only the names of the first two timers are passed correctly. From the third timer onwards, the name of the second timer is always passed.

Example:
Timer 1 = pizza timer
Timer 2 = tea timer
Timer 3 = bun timer

But in the adapter the third timer is also called tea timer.

**Comment by MiRo1310** [comment]
Werde ich mir anschauen.

**Comment by Heinz2100** [comment]
Danke und kein Stress. Der Adapter ist super und ich schreibe es nur rein, damit er noch besser wird. Viele Grüße

**Comment by Heinz2100** [comment]
Danke für die schnelle Bearbeitung, aber die Namensübergabe funktioniert jetzt irgendwie gar nicht mehr. Der Name wird nicht mehr aktualisiert. Somit funktioniert auch das beenden der Timer via Datenpunkt reset nicht mehr.

**Comment by Heinz2100** [comment]
Und andersherum laufen die Timer im Adapter weiter, obwohl sie auf Alexa schon gecancelt wurden

**Comment by Heinz2100** [comment]
Hallo,

Danke schon einmal für dein Update. Ich will dich ja nicht in den Wahnsinn treiben, aber nach mehreren Testläufen als Feedback zum aktuellen Update:

Bei mir klappt es mit dem Timer-Namen und somit auch mit dem Reset via Datenpunkt noch immer nicht. Der Erste Timer funktioniert noch absolut zuverlässig und fehlerfrei. Bei den weiteren wird der Name nur selten korrekt übergeben.

Ablauf Beispiel:
Timer 1: Tee Timer 10 Minuten
Timer 2: Pizza Timer 25 Minuten
Timer 3: Kuchen Timer 40 Minuten
Timer 4: Braten Timer 50 Minuten
Alles gelöscht

Danach neuer Durchlauf:
Timer 1: Limonaden Timer 10 Minuten
Timer 2: Wasser Timer 25 Minuten
Timer 3: Bier Timer 40 Minuten (Name im Adapter = Wasser Timer)
Timer 4: Cocktail Timer 50 Minuten (Name im Adapter = Wasser Timer)

Danach neuer Durchlauf (seltener):
Timer 1: Baguette Timer 10 Minuten
Timer 2: Toast Timer 25 Minuten (Name im Adapter = Baguette Timer)
Timer 3: Wurst Timer 40 Minuten (Name im Adapter = Baguette Timer)
Timer 4: Käse Timer 50 Minuten (Name im Adapter = Baguette Timer)



Interessant ist, dass sogar für eine Sekunde der korrekte Name angezeigt wird und es dann falsch mit den Namen vorheriger Timer überschrieben wird.

Nur als Feedback. Vielen Dank und viele Grüße

**Comment by MiRo1310** [comment]
😂 Das ist ja verflucht. Ich bin aber dran.

**Comment by Heinz2100** [comment]
Ist bestimmt nicht einfach 🙈Danke dir

**Comment by MiRo1310** [comment]
Wenn du magst kannst du gerne einmal direkt aus dem Pull Request installieren und testen. Das ist der Link `https://github.com/MiRo1310/ioBroker.alexa-timer-vis/tree/FIX-%23137`

**Comment by MiRo1310** [comment]
Da scheinen doch noch mehr Fehler drin zu sein, ich werde mich da morgen noch mal drum kümmern. Also brauchst du noch nichts zu machen

**Comment by Heinz2100** [comment]
Danke schon einmal. Mach dir nicht zu viel Stress 🙏🏻

**Comment by MiRo1310** [comment]
Wenn du testen magst kannst du über diesen Link installieren. https://github.com/MiRo1310/ioBroker.alexa-timer-vis/tree/FIX--%23137

**Comment by Heinz2100** [comment]
Hallo, schon einmal vielen Dank.

Die Namen funktionieren jetzt soweit ich es getestet habe. Nur noch folgendes:
- Beim Reset des dritten Timers über den Datenpunkt sagt Alexa "du hast mehrere Timer gestellt... welchen möchtest du löschen?" Da scheint der Name zum Resetten nicht korrekt übergeben zu werden. Bei den anderen Timern (1,2 und 4) funktioniert es problemlos.
- Der Datenpunkt all_Timer - Alive steht bei mir immer auf true; egal ob es Timer gibt oder nicht

**Comment by Heinz2100** [comment]
Timer 3 Reset hat jetzt komischerweise auch funktionier nach mehrmaligem Test.
Bleibt dann momentan nur noch der Punkt mit all-Timer Alive = true, obwohl keiner gestellt

**Comment by MiRo1310** [comment]
Okay, manchmal verstehe ich das selber nicht warum es nicht funktioniert. Ich werde nochmals schauen was sich finden lässt. Eigentlich hatten ich das Problem mit dem all timer-alive doch schon gelöst, komisch. Aber es wird immer besser, hoffe ich

**Comment by Heinz2100** [comment]
Ne ist echt schon super und ein toller Adapter. Vielen Dank dafür. Ich kann notfalls einstweilen auch einen Workaround mit Blockly und einem eigenen Datenpunkt machen. Wenn kein Timer dann false. Also kein Stress

**Comment by MiRo1310** [comment]
Ne ich bin ja dran.

**Comment by MiRo1310** [comment]
So jetzt sollte auch das funktionieren. Bitte noch einmal testen

**Comment by Heinz2100** [comment]
Guten Morgen, jetzt klappt bei mir alles perfekt. Vielen Dank für deine Hilfe bzw. fürs schnelle Weiterentwickeln.

**Comment by MiRo1310** [comment]
Okay top. Wenn wieder ein Problem auftaucht einfach neues Issue auf machen.
