### ISSUE TITLE
All timer alive steht zu Beginn auf true, obwohl keine Timer gestellt

### ISSUE THREAD

**Issue by Heinz2100** [MiRo1310/ioBroker.alexa-timer-vis#134]
Ich nutze Version 2.0.2

Wenn man die Instanz neu startet, dann steht bei mir der Datenpunkt "All timer alive" auf "true", obwohl keine Timer gestellt sind.

**Comment by MiRo1310** [comment]
Stimmt das habe ich auch schon gesehen. Gut das du ein Issue erstellt hast.
