### ISSUE TITLE
"Entprellen" bei mehreren Echo-Geräten

### ISSUE THREAD

**Issue by BernhardLinz** [MiRo1310/ioBroker.alexa-timer-vis#14]
Ich nutze den Timer - und die Anzeige dieser auf einem Tablet dort über diesen Adapter - hauptsächlich in der Küche.

Nun kann es sein das gleich mehrere Geräte den Befehl dazu gleichzeitig erfassen ohne sich schon geeinigt zu haben wer von denen das verarbeiten soll. Bei mir hören das dann z.B. das Gerät in der Küche, im Wohnzimmer, im Gäste-WC und auf dem Flur im Erdgeschoss. Wenn ich lauter gesprochen haben auch noch Schlafzimmer und Badezimmer ...

Mittel der Amazon-Logik einigen die sich aber und nur der aus der Küche (weil am nächsten dran) wird aktiv. Oder der im Flur. Aber halt nur einer.

Der Adapter erzeugt aber manchmal (nicht immer, ich versuche leiser zu sprechen ...) dann 2 bis 4 Timer mit wenigen Sekunden Abstand.
Soweit ich es verstanden habe achtet er halt auch auf die Schlüsselwörter. Im History-Feld kommen ggf. halt alle Echos die es gerade gehört haben mit dem gleichen Satz hintereinander. Wie beschrieben macht die Amazon-Logik dann trotzdem einen Eintrag daraus.

In einem normalen ioBroker-Skript würde ich nun entprellen, sprich der erste reagiert und blockiert/ignoriert weitere Anfrage für z.B. 3 Sekunden.

Eventuell könnte man so etwas als Option einführen mit einer konfigurierbaren Zeitspanne.

**Comment by MiRo1310** [comment]
Das ist entprellt für 20 sek. Bzw vergleiche ich das gesprochene wenn das nicht gleich ist, d.h. Ich stelle einen anderen Timer kann ich das sofort machen. 
Jetzt ist mir aber auf gefallen das bei dir immer ausgegeben wird "stelle timer " und dann "stelle Timer auf 4 Minuten ", dann genau so noch einmal. Dadurch wird natürlich mein entprell timeout übergangen. 
Ich habe aber eine Idee, indem ich garnicht Menü auf stelle Timer reagiere.

**Comment by BernhardLinz** [comment]
Ich will nicht ausschließen das die einzelnen Geräte das ggf. leicht anderes verstehen (je nach Akustik).
Bin mal gespannt.

**Comment by MiRo1310** [comment]
@BernhardLinz 
In den Objekten kannst du doch sehen von welchem Echo der Timer erstellt wurde. 
Ich werde die Logik auf jeden Fall noch ein bisschen anpassen. Und dann musst du noch mal testen. Ich weiß nicht ob ich das heute noch schaffe. Ansonsten am Wochenende.

**Comment by BernhardLinz** [comment]
Das lasse ich mir sogar mit anzeigen. wenn ich da 3 Timer habe obwohl ich nur einen wollte dann haben die so einen Versatz von 2 bis 3 Sekunden zwischen den einzelnen Timern und jeder wurde von einem anderen Gerät erzeugt. Auf den Text  muss ich mal achten

**Comment by MiRo1310** [comment]
@BernhardLinz Warum denn jetzt ein neues issue? Bezieht sich doch beides auf das gleiche. 🤔

**Comment by MiRo1310** [comment]
@BernhardLinz 
Kannst du mal den Adapter auf debug log stellen und das log posten.

**Comment by MiRo1310** [comment]
@BernhardLinz 
Ich vermute ist das gleiche Problem wie #12

**Comment by BernhardLinz** [comment]
Aber dann halt dadurch ausgelöst das mehrere Geräte gleichzeitig zuhören

Debug muss ich mal schauen ... muss ja in der Küche sein um das zu testen, ich versuche es heute Abend zu schaffen

**Comment by MiRo1310** [comment]
Ja genau. 
Ich habe gerade bei #12 ins log geschaut, tatsächlich haben dort 2 Geräte den Timer gestellt. 
Wenn ich dein log bekomme vergleiche ich das mal.

**Comment by MiRo1310** [comment]
@BernhardLinz 
Bitte einmal probieren ob es so funktioniert, wenn nicht kann man jetzt in der Admin Oberfläche des Adapters die Entprellzeit einstellen, bzw habe ich eine checkbox hinzugefügt, die jegliche eingabe in der eingestellten Zeit unterbindet.

**Comment by BernhardLinz** [comment]
Verzeih das ich mich nicht mehr gemeldet habe. Mit der neuen Option und einer Entprellzeit von 10 Sekunden scheint das Problem weg zu sein. Er weist zwar nicht immer das Gerät aus welches den Timer dann auch meldet, dafür aber nur einmal.

Die neueren Echo-Geräte scheinen Fixer zu sein und somit zuerst zu reagieren, in der Küche wo ich es hauptsächlich nutze ist noch einer der allerersten Echos
