### ISSUE TITLE
Die Eingabe ist ungültig. Bitte Issue erstellen

### ISSUE THREAD

**Issue by denjo82** [MiRo1310/ioBroker.alexa-timer-vis#15]
Bekomme immer diese Fehlermeldung wenn ich einen Wecker stelle:

Die Eingabe ist ungültig. Bitte Issue erstellen

**Comment by MiRo1310** [comment]
Kannst du bitte einmal das log dazu posten?

**Comment by denjo82** [comment]
Das ist der log

**Comment by MiRo1310** [comment]
@denjo82 
ist kein log da

du könntest auch von github die neuste version laden und schauen ob das Problem auch noch da ist? Ich habe einiges geändert, und bei mit taucht der Fehler nicht auf

Ich habe zudem den Code noch etwas angepasst, der Wecker sollte nicht mehr beachtet werden

**Comment by denjo1982** [comment]
alexa-timer-vis.0 | 2022-10-08 11:11:54.441 | error | Die Eingabe ist ungültig. Bitte Issue erstellen

ich habe version 0.1.15

**Comment by MiRo1310** [comment]
Einmal über die Katze installieren mit https://github.com/MiRo1310/ioBroker.alexa-timer-vis.git

**Comment by denjo1982** [comment]
problem besteht weiterhin

und trotzdem version 0.1.15

**Comment by MiRo1310** [comment]
@denjo82 
Ok dann bitte einmal das log des Adapters auf debug stellen und das komplette log hier posten. Nicht nur die Fehlermeldung.

**Comment by denjo1982** [comment]
<html>
<body>


alexa-timer-vis.0 | 2022-10-08 13:50:48.174 | debug | [{"CreationTime":1665229846725},{"OldCreationTime":1665229845206},{"Serial":"G0014D0594860AMQ"},{"OldSerial":"G2A0QU06819400U2"}]
-- | -- | -- | --
alexa-timer-vis.0 | 2022-10-08 13:50:48.042 | error | Die Eingabe ist ungültig. Bitte Issue erstellen
alexa-timer-vis.0 | 2022-10-08 13:50:48.041 | debug | ValueOld: null
alexa-timer-vis.0 | 2022-10-08 13:50:48.040 | debug | Start value: "stell den wecker auf fünfzehn uhr fünfzig"
alexa-timer-vis.0 | 2022-10-08 13:50:48.040 | debug | ---------------------Start------------------------------
alexa-timer-vis.0 | 2022-10-08 13:50:46.695 | debug | [{"CreationTime":1665229845206},{"OldCreationTime":1665229836668},{"Serial":"G2A0QU06819400U2"},{"OldSerial":"G2A0QU06819400U2"}]
alexa-timer-vis.0 | 2022-10-08 13:50:46.538 | debug | ValueOld: null
alexa-timer-vis.0 | 2022-10-08 13:50:46.538 | debug | Start value: "stell den wecker"
alexa-timer-vis.0 | 2022-10-08 13:50:46.537 | debug | ---------------------Start------------------------------


</body>
</html>

**Comment by MiRo1310** [comment]
@denjo82 Ok vielen Dank. Ich weiß schon wo der Fehler liegt. Melde mich , spätestens morgen

**Comment by MiRo1310** [comment]
@denjo1982 Der Fehler sollte behoben sein

**Comment by denjo1982** [comment]
yes, keine fehlermeldung mehr. danke

**Comment by MiRo1310** [comment]
Perfekt !!!!
