### ISSUE TITLE
Error: Unexpected end of input

### ISSUE THREAD

**Issue by BeSiRe1** [MiRo1310/ioBroker.alexa-timer-vis#156]
Hallo,

seit dem Update auf Version 2.0.5 funktioniert der Adapter bei mir nicht mehr.
Folgende Fehler habe ich im Log:

![Alexa Timer vis](https://github.com/user-attachments/assets/939ea43a-93ae-46b0-89d0-648ca5fa58cc)

Alexa2 Version 3.26.5
Node.js Version: 20.18.0

Brauchst du sonst noch Angaben?

**Comment by MiRo1310** [comment]
Hi. Bei allen Eingaben ? Oder nur bei einer bestimmten Eingabe?

**Comment by BeSiRe1** [comment]
WIr starten den Timer immer gleich. Alexa setzen einen Timer auf 10 Minuten. z.B.
Oder was meinst du genau?

**Comment by MiRo1310** [comment]
Okay. Werde ich mir anschauen

**Comment by BeSiRe1** [comment]
Besten Dank

**Comment by MiRo1310** [comment]
Ich habe gerade versucht den Fehler nach zu stellen, ich bekomme diesen Fehler aber nicht. Du könntest mir mal den genauen wert geben der in alexa.x.history.summary steht

**Comment by BeSiRe1** [comment]
Der genaue Wert ist: setze ein timer auf fünfzehn minuten
Damit hat es von 10 Versuchen drei mal richtig funktioniert, 5 mal wurde ein Timer über Alexa gestartet aber der ALEXA Timer Adapter hat nicht reagiert und 2 mal habe ich den Fehler bekommen.

**Comment by MiRo1310** [comment]
Kannst du einmal von Github installieren? Ich habe die Fehlermessage etwas erweitert. Und dann das Log noch mal posten?

**Comment by BeSiRe1** [comment]
Sorry das ich jetzt erst Antworte.
Habe die neue Version von Github installiert.
Seitdem ist mein Log sauber aber der Adapter bekommt nur ca. jeden dritten Timer mit. 
Beim Rest startet Alexa einen Timer aber der Adapter reagiert nicht.

**Comment by MiRo1310** [comment]
Okay. Ich habe das auch schon gesehen das nicht alle erfasst werden. Wenn ich am Rechner sitze läuft natürlich immer alles. Werde mir das aber noch mal anschauen. Was auch sein könnte das das setzten des Timers nicht im Alexa Adapter aktualisiert wird.

**Comment by MiRo1310** [comment]
Ich habe schon mal einen Fehler gefunden und gefixt

**Comment by BeSiRe1** [comment]
sehr  gut. kann man die neue Version über Github laden?

**Comment by MiRo1310** [comment]
Ja kann man. Ich habe auch noch ein paar zusätzliche log Ausgaben hinzugefügt. Ich bin aber auch selbst am schauen

**Comment by MiRo1310** [comment]
Ich habe noch wieder ein paar Anpassungen gemacht, kannst du gerade noch mal updaten von Github. Ich werde das gleichzeitig aus testen

**Comment by BeSiRe1** [comment]
Habe es gerade aktualisiert. Werde die nächsten Tage Rückmeldung geben. Vielen Dank für deine Arbeit

**Comment by MiRo1310** [comment]
Gerne. Ich möchte ja auch das es funktioniert.

**Comment by MiRo1310** [comment]
Wie schaut es aktuell aus?
