### ISSUE TITLE
@Bjoern-W

### ISSUE THREAD

**Issue by MiRo1310** [MiRo1310/ioBroker.alexa-timer-vis#16]
@Bjoern-W 
Achso , also verstehe ich das so richtig wenn du einen 5 Minuten Timer stellst , soll in einem datenpunkt 5 Minuten stehen? 
Als Zahl also nur 5 oder als String 5 Minuten ? Oder noch anders ? 

__Originally posted by @MiRo1310 in https://github.com/MiRo1310/ioBroker.alexa-timer-vis/issues/12#issuecomment-1275130973__

**Comment by MiRo1310** [comment]
@Bjoern-W
jetzt kannst du das auch mal testen, was man noch anpassen könnte wären die Einheiten. Am besten das mman das im Admin einstellen kann

**Comment by MiRo1310** [comment]
Einheiten können jetzt in der Admin Oberfläche von User eingestellt werden. 
Den neuen Datenpunkt hattest du ja schon gefunden. 
Timer mit 4 ein halb Minuten oder ähnlich geht auch

**Comment by Bjoern-W** [comment]
Ich bin dann jetzt auch raus, ich habe ja geschrieben das ich ab morgen für 6 Monate im Ausland sein werde und heute habe ich noch so einiges auf dem Zettel.
Sollten im halben Jahr noch Probleme mit dem Adapter vorhanden sein kann ich gerne wieder für dich testen.
Bis dahin wünsche ich dir eine gut Zeit.

**Comment by MiRo1310** [comment]
@Bjoern-W 
viel Erfolg, hab eine gute Zeit, kannst ja wenn nötig wieder ein Issue erstellen.
Und nochmals vielen Dank für dein durchhaltevermögen als tester

**Comment by Bjoern-W** [comment]
gern geschehen
