### ISSUE TITLE
Fortschritt in Prozent

### ISSUE THREAD

**Issue by flo225** [MiRo1310/ioBroker.alexa-timer-vis#17]
Hallo,

großes Lob an den Adapter, es funktioniert alles wunderbar.
Für die Zukunft hätte ich folgenden Verbesserungsvorschlag:
Prozentualer Fortschritt des Timers in Prozent für die Darstellung der Visualisierung. Ist sowas denkbar?

Besten Dank und Gruß
Flo

**Comment by MiRo1310** [comment]
So ich habe die Prozente eingefügt, gerne einmal testen

**Comment by flo225** [comment]
Funktioniert wunderbar, vielen Dank!
