### ISSUE TITLE
Please check versions

### ISSUE THREAD

**Issue by mcm1957** [MiRo1310/ioBroker.alexa-timer-vis#42]
Release 0.1.15 is not available at npm and not listed at latest repository while available via github and used by several users.
Thats unusual - although not forbidden.

If this is on purpose, ignore this issue - otherwise, please check deployment.

**Comment by MiRo1310** [comment]
Ich habe die Version erstellt. Ich wusste garnicht das ich das schon hatte. 🙈 Erstelle ich einfach einen neuen Pull Request?
