### ISSUE TITLE
Timer mit Namen wird nicht abgebrochen

### ISSUE THREAD

**Issue by rtwl21** [MiRo1310/ioBroker.alexa-timer-vis#57]
Ich hatte bei 3 Versuchen immer das Problem, dass der Timer nicht mit dem "Reset" Button abgebrochen werden kann.
Timer gestellt mit "Toast Timer 6 Minuten"
der Timer wurde korrekt gestellt und angezeigt. 
Beim Resetten durch den Button kommt die Ansage, dass bereits ein Timer mit dem Namen "Toast" existiert. Im Alexa2.0 Adapter sehe ich, dass der Befehlt "stoppe toast 6Minuten  Timer" gesendet wird. Ändere ich die falsche Positionierung der Leerzeichen, also auf "stoppe toast 6 Minuten Timer", funktioniert das Abbrechen des Timer.

**Comment by MiRo1310** [comment]
Wie benutzt du den Button denn? Wenn ich den Button mit true aktualisiere wird der Timer abgebrochen

**Comment by rtwl21** [comment]
egal ob ich mit vis den state auf true schreibe oder in den Objekten klicke direkt den Button klicke. Immer selbes Ergebnis.
hast du es mit dem selben Befehl probiert wie ich (Alexa, Toast timer 6 Minuten)?
mir ist dann eben aufgefallen, dass ein Leerzeichen falsch gesetzt wird beim Abbruch Befehl.
kann ich weitere Infos bereitstellen?

**Comment by MiRo1310** [comment]
Kommt denn ein Fehler im log? Ich kann das leider nicht nachstellen.

**Comment by rtwl21** [comment]
Nein, leider kommt im Log kein Fehler. Laut log sieht es so aus, als ob der timer auch gestoppt wird. Bei alexa läuft er auch weiter. klicke ich ein zweites Mal auf den Button, kommt von alexa die Ansage, dass schon ein Timer mit dem Namen 'Toast' existiert und ich einen anderen Namen wählen soll.

**Comment by rtwl21** [comment]
Ich hab jetzt nochmals intensiv getestet und konnte den Fehler nicht wieder reproduzieren. Gestern abend war immer ein Fehler, genauso sie heute Nachmittag bei einem realen Timer. Jetzt aber funktioniert es jedesmal.
ich werde weiter beobachten und berichten. aktuell schiebe ich mal den Fehler Richtung Alexa.
danke vorerst.
