### ISSUE TITLE
neuer "String" ohne Stunden gewünscht

### ISSUE THREAD

**Issue by rtwl21** [MiRo1310/ioBroker.alexa-timer-vis#58]
Ich würde mir ein neues "String" Objekt wünschen bzw das akuelle etwas anpassen.
Wenn die Stunden 00 sind, hätte ich gerne "00:00 min" als String anstelle von "00:00:00 min". Da es vielleicht manche nicht wollen, wäre ein "String2" Objekt vielleicht ganz hilfreich. Bei 1 Std 5 Min könnte dann ja 65:00 min stehen. Nur so als Idee.

Zusätzlich könnte ich es für die VIS gebrauchen, dass die Objekte "hour", "minute", "second" geleert werden, wenn kein Timer gestellt ist. Also keine "00" stehen bleiben. Da man in der VIS leider nicht 2 Objekte als bedingung der Sichtbarkeit einstellen kann. Ich hätte gerne die Sekunden angezeigt, wenn unter einer Minute Rest sind.

Danke

**Comment by MiRo1310** [comment]
Bitte einmal von Github installieren und testen

**Comment by rtwl21** [comment]
Funktioniert wie erwartet - zumindest der string_2 ist optimal. Danke dafür 👍
Wenn die objekte ``hour`` ``minute`` und ``second`` noch geleert werden könnten wenn der Timer nicht aktiv ist, wäre ich wunschlos glücklich!

**Comment by MiRo1310** [comment]
Bitte noch einmal testen

**Comment by rtwl21** [comment]
Sehr gut, danke 👍🏼
die 3 Objekte sind nun leer, was mir für die Sichtbarkeit Bedingung in der VIS sehr hilft
