### ISSUE TITLE
Fehler bei benutzerdefinierte Einstellungen Datenpunkte

### ISSUE THREAD

**Issue by fornax76-git** [MiRo1310/ioBroker.alexa-timer-vis#6]
Mir ist aufgefallen, dass bei den benutzerdefinierten Einstellungen der Datenpunkte (Zahnrad)
ein Fehler vom alexa-timer-vis Adapter auftaucht.

`Cannot load jsonConfig of alexa-timer-vis: not exists`

Der Fehler erscheint bei allen Datenpunkten, unabhängig von der Herkunft des Datenpunktes

**Comment by MiRo1310** [comment]
@fornax76-git 

Aktualisiere den Adapter mal, diese Funktion sollte im Adapter garnicht ein gebaut sein. 
Hatte ich bereits aus dem Code gelöscht.

**Comment by fornax76-git** [comment]
> @fornax76-git
> 
> Aktualisiere den Adapter mal, diese Funktion sollte im Adapter garnicht ein gebaut sein. Hatte ich bereits aus dem Code gelöscht.

Oh sorry. Hatte nicht gesehen, dass es schon die 0.1.10 gibt.
Jetzt passt es!
Danke
