### ISSUE TITLE
Feature Request - Name des Alexa-Gerätes im Baum des Adapters

### ISSUE THREAD

**Issue by Siggi0904** [MiRo1310/ioBroker.alexa-timer-vis#71]
Hallo,
aktuell wird die Baumstruktur nur mit "timer1", "timer2" etc. je nach Alexa-Geräten  erstellt.

Schön wäre, wenn der Adapter den Gerätenamen dazuschreiben würde.
Also z.B. "Wohnzimmer - Timer", "Schlafzimmer - Timer1" etc.

Danke im Voraus.

**Comment by MiRo1310** [comment]
Dazu gibt es doch einen datenpunkt der das gerät ausliest, das müsste man dann selbst als text sich zusammen stellen.

**Comment by Siggi0904** [comment]
Nur der Übersichtlichkeit wegen. Macht das Finden des aktuellen Timers einfacher.

**Comment by MiRo1310** [comment]
Das möchte aber sicherlich nicht jeder, deswegen alles einzeln, wo willst du denn was finden? Um das in der Vis dazustellen?

**Comment by Siggi0904** [comment]
Wenn z.B. 3 Timer aktiv laufen müssen alle Bäume aufgeklappt werden, um den betreffenden Timer zu sehen.
Oder fügt der Adapter den letzten erstellten Timer immer hinten an?

Dann war mein Verständnis falsch und der FR kann gelöscht werden.

**Comment by MiRo1310** [comment]
Nein der Timer wird immer an den nächsten freien Platz gesetzt, haste 3 timer und timer 2 ist zuende und erstellst danach einen neuen kommt der an platz 2 ansonsten wenn alle noch laufen an 4. 
Ich überlege mal!
