### ISSUE TITLE
Keine Timer

### ISSUE THREAD

**Issue by Mephisto090** [MiRo1310/ioBroker.alexa-timer-vis#73]
Hej,

ich habe einen Timer bei Alexa erstellt und im Alexa2 Adapter wird er auch angezeigt. Es wird aber leider nicht in deinem Adapter angezeigt. Ich habe viele Alexas. :)

![image](https://github.com/MiRo1310/ioBroker.alexa-timer-vis/assets/85995176/0ed8bf53-27e1-43b5-8a26-f0e0a05a2fb2)
Alexa2 Adapter

VG

**Comment by MiRo1310** [comment]
Wird der Sunmary Datenpunkt auch aktualisiert?

**Comment by Mephisto090** [comment]
welchen meinst du?

**Comment by Mephisto090** [comment]
![image](https://github.com/MiRo1310/ioBroker.alexa-timer-vis/assets/85995176/779872fd-465c-454c-84eb-61f6d5b570eb)

**Comment by MiRo1310** [comment]
Ja genau summary im Alexa 2 Adapter

**Comment by Mephisto090** [comment]
> Ja genau summary im Alexa 2 Adapter

welchen meinst du? Hast du ein Screen oder Pfad zum gesuchten?

**Comment by MiRo1310** [comment]
alexa2.0.History.summary

**Comment by Mephisto090** [comment]
Ja da steht mein letzt gesagtes drin

**Comment by MiRo1310** [comment]
Und was steht im log von meinem adapter? bitte auf debug stellen

**Comment by Mephisto090** [comment]
Er funktioniert jetzt... warum auch immer. Mir ist aber aufgefallen, wenn ich den timer im script selbst resete wird er nicht neu hinzugefügt. Ich habe ihn in den letzten 5 Sekunden resetet, falls das eine rolle spielt

**Comment by Mephisto090** [comment]
Jetzt habe ich es irgendwie geschafft das das summery nicht aktualisiert wurde. Es ist immer noch mein Befehl davor "Stopp". Der Alexa2 Adapter hat mein "Befehl" irgendwie nicht mitbekommen. Der Timer läuft aber auf der Physischen Alexa

**Comment by MiRo1310** [comment]
Installiere mal latest vom Alexa2 Adapter, da gab es eine Änderung

**Comment by Mephisto090** [comment]
Hatte ich bereits
![image](https://github.com/MiRo1310/ioBroker.alexa-timer-vis/assets/85995176/04a4efbd-74d6-4037-9f1f-e5f841be4a9e)

**Comment by MiRo1310** [comment]
Ich habe im Moment 3.25.5 , bisher scheint es da zu gehen. 
Probiere mal aus.

**Comment by Mephisto090** [comment]
Du kannst ja ein Update machen und schauen ob es auf der neuen auch geht :D :D

**Comment by MiRo1310** [comment]
ich habe das Update gemacht, scheint sporadisch zu funktionieren

Und du musst das im Alexa2 Adapter aktivieren. Steht so in der UpdateInfo

**Comment by MiRo1310** [comment]
Ich habe jetzt ein paar Features gebaut, und da hat die neue Version von Alexa2 gelaufen. Daher schliesse ich das hier mal
