### ISSUE TITLE
Timer läuft nach

### ISSUE THREAD

**Issue by Mephisto090** [MiRo1310/ioBroker.alexa-timer-vis#74]
Hallo,

der Timer auf der Alexa ist z.b. bei 9:00min und der Timer im Adapter bei 9:07min, sodass der Timer circa 6 - 8 Sekunden nach läuft.
Ist das Normal oder nicht anders möglich? 

VG

**Comment by MiRo1310** [comment]
Das Problem ist das ich auf den datenpunkt summary reagiere. Wenn dieser erst später aktualisiert wird, besteht leider das Problem. 
Ich werde aber demnächst noch mal schauen.

**Comment by Mephisto090** [comment]
Kannst du dir nicht die Serial Nummer aus der History ziehen und danach die genaue Zeit hier raus?

Serial Nummer: `alexa2.0.History.serialNumber`

Genaue Zeit: `alexa2.0.Echo-Devices.G0916D0XXXXXXX.Timer.nextTimerDate` bzw. `alexa2.0.Echo-Devices.G0916D0XXXXXXX.Timer.activeTimerList`

Ich denke hier macht aber die TimerList mehr Sinn. Da es möglich ist mehr als nur 1 Timer zu stellen. :)

**Comment by MiRo1310** [comment]
Danke für die Info. Werde ich mir anschauen.
