### ISSUE TITLE
Wird nicht in den Objekten angezeigt

### ISSUE THREAD

**Issue by totocotonio** [MiRo1310/ioBroker.alexa-timer-vis#81]
Guten Tag,
Adapter installiert, wird auch grün, Objekte werden angelegt.

Starte ich jetzt einen Timer über eine Alexa, wird in den Objekten nichts angezeigt.

Ich bitte um Hilfe!

**Comment by MiRo1310** [comment]
Das Problem ist bekannt, damit der Adapter arbeiten kann muss der summary datenpunkt im alexa2 adapter aktualisieren. Dazu muss man dieses inzwischen im Alexa2 adapter aktivieren

**Comment by totocotonio** [comment]
> Das Problem ist bekannt, damit der Adapter arbeiten kann muss der summary datenpunkt im alexa2 adapter aktualisieren. Dazu muss man dieses inzwischen im Alexa2 adapter aktivieren

Darf ich fragen wo das gemacht wird

**Comment by MiRo1310** [comment]
im Alexa2 adapter in den Einstellungen unter Synchronisierungseinstellungen, ob der Summary Datenpunkt da aber drunter fällt kann ich nicht sagen, aber danach lief es einigermaßen. Ich suche aber noch eine Lösung dazu

**Comment by totocotonio** [comment]
ok, danke, dann suche ich einmal nach.

Vielen Dank für die Hilfe
