### ISSUE TITLE
Datenpunkt reset stoppt timer im Adapter nicht

### ISSUE THREAD

**Issue by Siggi0904** [MiRo1310/ioBroker.alexa-timer-vis#82]
wenn ich einen aktiven Timer mit dem Objekt "reset" im iobroker stoppe,
wird der Timer in der Alexa zwar gestoppt, läufter aber im IOBroker weiter.

Dann geht nur auslaufen lassen oder Instanz neustarten.

**Comment by MiRo1310** [comment]
Schaue ich mir an

**Comment by MiRo1310** [comment]
Ich habe mir das angeschaut und das Problem ist, das der Datenpunkt Summary in Alexa2 Adapter nicht richtig aktualisiert wird
